######################## default configuration ####################
baseURL = "https://flamboyant-mcclintock-23455b.netlify.app"
languageCode = "en-us"
title = "Red Hat Developer Advocacy | UK & Ireland"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

  # main menu
    [[menu.main]]
  name = "Usergroups"
  URL = "ocp"
  weight = 1

  [[menu.main]]
  name = "About Us"
  URL = "about"
  weight = 2

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 3

  [[menu.main]]
  name = "Join us"
  URL = "contact"
  weight = 4

  # footer menu
  [[menu.footer]]
  name = "About Us"
  URL = "about"
  weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Red Hat Developer Advocacy | UK & Ireland"
author = "Florian Moss"
# Google Analitycs
googleAnalyticsID = "G-VE878Y7TJY"
# Contact Information
email = "uki-developers@redhat.com"
location = "UK & Ireland"
# copyright
copyright = ""

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################# social site ########################

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/openshift"

[[params.social]]
title = "twitter"
icon = "ti-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/openshift"
